# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20150708_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score2009',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', primary_key=True, serialize=False)),
                ('SSc1', models.IntegerField(null=True)),
                ('SSc2', models.IntegerField(null=True)),
                ('SSc3', models.IntegerField(null=True)),
                ('SSc4_1', models.IntegerField(null=True)),
                ('SSc4_2', models.IntegerField(null=True)),
                ('SSc4_3', models.IntegerField(null=True)),
                ('SSc4_4', models.IntegerField(null=True)),
                ('SSc5_1', models.IntegerField(null=True)),
                ('SSc5_2', models.IntegerField(null=True)),
                ('SSc6_1', models.IntegerField(null=True)),
                ('SSc6_2', models.IntegerField(null=True)),
                ('SSc7_1', models.IntegerField(null=True)),
                ('SSc7_2', models.IntegerField(null=True)),
                ('SSc8', models.IntegerField(null=True)),
                ('WEc1', models.IntegerField(null=True)),
                ('WEc2', models.IntegerField(null=True)),
                ('WEc3', models.IntegerField(null=True)),
                ('EAc1', models.IntegerField(null=True)),
                ('EAc2', models.IntegerField(null=True)),
                ('EAc3', models.IntegerField(null=True)),
                ('EAc4', models.IntegerField(null=True)),
                ('EAc5', models.IntegerField(null=True)),
                ('EAc6', models.IntegerField(null=True)),
                ('MRc1_1', models.IntegerField(null=True)),
                ('MRc1_2', models.IntegerField(null=True)),
                ('MRc2', models.IntegerField(null=True)),
                ('MRc3', models.IntegerField(null=True)),
                ('MRc4', models.IntegerField(null=True)),
                ('MRc5', models.IntegerField(null=True)),
                ('MRc6', models.IntegerField(null=True)),
                ('MRc7', models.IntegerField(null=True)),
                ('EQc1', models.IntegerField(null=True)),
                ('EQc2', models.IntegerField(null=True)),
                ('EQc3_1', models.IntegerField(null=True)),
                ('EQc3_2', models.IntegerField(null=True)),
                ('EQc4_1', models.IntegerField(null=True)),
                ('EQc4_2', models.IntegerField(null=True)),
                ('EQc4_3', models.IntegerField(null=True)),
                ('EQc4_4', models.IntegerField(null=True)),
                ('EQc5', models.IntegerField(null=True)),
                ('EQc6_1', models.IntegerField(null=True)),
                ('EQc6_2', models.IntegerField(null=True)),
                ('EQc7_1', models.IntegerField(null=True)),
                ('EQc7_2', models.IntegerField(null=True)),
                ('EQc8_1', models.IntegerField(null=True)),
                ('EQc8_2', models.IntegerField(null=True)),
                ('IDc1', models.IntegerField(null=True)),
                ('IDc2', models.IntegerField(null=True)),
                ('Extra1', models.IntegerField(null=True)),
                ('Extra2', models.IntegerField(null=True)),
                ('Extra3', models.IntegerField(null=True)),
                ('Extra4', models.IntegerField(null=True)),
                ('project', models.OneToOneField(to='api.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreTwoPointOne',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', primary_key=True, serialize=False)),
                ('SSc1', models.IntegerField(null=True)),
                ('SSc2', models.IntegerField(null=True)),
                ('SSc3', models.IntegerField(null=True)),
                ('SSc4_1', models.IntegerField(null=True)),
                ('SSc4_2', models.IntegerField(null=True)),
                ('SSc4_3', models.IntegerField(null=True)),
                ('SSc4_4', models.IntegerField(null=True)),
                ('SSc5_1', models.IntegerField(null=True)),
                ('SSc5_2', models.IntegerField(null=True)),
                ('SSc6_1', models.IntegerField(null=True)),
                ('SSc6_2', models.IntegerField(null=True)),
                ('SSc7_1', models.IntegerField(null=True)),
                ('SSc7_2', models.IntegerField(null=True)),
                ('SSc8', models.IntegerField(null=True)),
                ('WEc1_1', models.IntegerField(null=True)),
                ('WEc1_2', models.IntegerField(null=True)),
                ('WEc2', models.IntegerField(null=True)),
                ('WEc3_1', models.IntegerField(null=True)),
                ('WEc3_2', models.IntegerField(null=True)),
                ('EAc1', models.IntegerField(null=True)),
                ('EAc2_1', models.IntegerField(null=True)),
                ('EAc2_2', models.IntegerField(null=True)),
                ('EAc2_3', models.IntegerField(null=True)),
                ('EAc3', models.IntegerField(null=True)),
                ('EAc4', models.IntegerField(null=True)),
                ('EAc5', models.IntegerField(null=True)),
                ('EAc6', models.IntegerField(null=True)),
                ('MRc1_1', models.IntegerField(null=True)),
                ('MRc1_2', models.IntegerField(null=True)),
                ('MRc1_3', models.IntegerField(null=True)),
                ('MRc2_1', models.IntegerField(null=True)),
                ('MRc2_2', models.IntegerField(null=True)),
                ('MRc3_1', models.IntegerField(null=True)),
                ('MRc3_2', models.IntegerField(null=True)),
                ('MRc4_1', models.IntegerField(null=True)),
                ('MRc4_2', models.IntegerField(null=True)),
                ('MRc5_1', models.IntegerField(null=True)),
                ('MRc5_2', models.IntegerField(null=True)),
                ('MRc6', models.IntegerField(null=True)),
                ('MRc7', models.IntegerField(null=True)),
                ('EQc1', models.IntegerField(null=True)),
                ('EQc2', models.IntegerField(null=True)),
                ('EQc3_1', models.IntegerField(null=True)),
                ('EQc3_2', models.IntegerField(null=True)),
                ('EQc4_1', models.IntegerField(null=True)),
                ('EQc4_2', models.IntegerField(null=True)),
                ('EQc4_3', models.IntegerField(null=True)),
                ('EQc4_4', models.IntegerField(null=True)),
                ('EQc5', models.IntegerField(null=True)),
                ('EQc6_1', models.IntegerField(null=True)),
                ('EQc6_2', models.IntegerField(null=True)),
                ('EQc7_1', models.IntegerField(null=True)),
                ('EQc7_2', models.IntegerField(null=True)),
                ('EQc8_1', models.IntegerField(null=True)),
                ('EQc8_2', models.IntegerField(null=True)),
                ('IDc1', models.IntegerField(null=True)),
                ('IDc2', models.IntegerField(null=True)),
                ('project', models.OneToOneField(to='api.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreTwoPointTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', primary_key=True, serialize=False)),
                ('SSc1', models.IntegerField(null=True)),
                ('SSc2', models.IntegerField(null=True)),
                ('SSc3', models.IntegerField(null=True)),
                ('SSc4_1', models.IntegerField(null=True)),
                ('SSc4_2', models.IntegerField(null=True)),
                ('SSc4_3', models.IntegerField(null=True)),
                ('SSc4_4', models.IntegerField(null=True)),
                ('SSc5_1', models.IntegerField(null=True)),
                ('SSc5_2', models.IntegerField(null=True)),
                ('SSc6_1', models.IntegerField(null=True)),
                ('SSc6_2', models.IntegerField(null=True)),
                ('SSc7_1', models.IntegerField(null=True)),
                ('SSc7_2', models.IntegerField(null=True)),
                ('SSc8', models.IntegerField(null=True)),
                ('WEc1_1', models.IntegerField(null=True)),
                ('WEc1_2', models.IntegerField(null=True)),
                ('WEc2', models.IntegerField(null=True)),
                ('WEc3_1', models.IntegerField(null=True)),
                ('WEc3_2', models.IntegerField(null=True)),
                ('EAc1', models.IntegerField(null=True)),
                ('EAc2', models.IntegerField(null=True)),
                ('EAc3', models.IntegerField(null=True)),
                ('EAc4', models.IntegerField(null=True)),
                ('EAc5', models.IntegerField(null=True)),
                ('EAc6', models.IntegerField(null=True)),
                ('MRc1_1', models.IntegerField(null=True)),
                ('MRc1_2', models.IntegerField(null=True)),
                ('MRc1_3', models.IntegerField(null=True)),
                ('MRc2_1', models.IntegerField(null=True)),
                ('MRc2_2', models.IntegerField(null=True)),
                ('MRc3_1', models.IntegerField(null=True)),
                ('MRc3_2', models.IntegerField(null=True)),
                ('MRc4_1', models.IntegerField(null=True)),
                ('MRc4_2', models.IntegerField(null=True)),
                ('MRc5_1', models.IntegerField(null=True)),
                ('MRc5_2', models.IntegerField(null=True)),
                ('MRc6', models.IntegerField(null=True)),
                ('MRc7', models.IntegerField(null=True)),
                ('EQc1', models.IntegerField(null=True)),
                ('EQc2', models.IntegerField(null=True)),
                ('EQc3_1', models.IntegerField(null=True)),
                ('EQc3_2', models.IntegerField(null=True)),
                ('EQc4_1', models.IntegerField(null=True)),
                ('EQc4_2', models.IntegerField(null=True)),
                ('EQc4_3', models.IntegerField(null=True)),
                ('EQc4_4', models.IntegerField(null=True)),
                ('EQc5', models.IntegerField(null=True)),
                ('EQc6_1', models.IntegerField(null=True)),
                ('EQc6_2', models.IntegerField(null=True)),
                ('EQc7_1', models.IntegerField(null=True)),
                ('EQc7_2', models.IntegerField(null=True)),
                ('EQc8_1', models.IntegerField(null=True)),
                ('EQc8_2', models.IntegerField(null=True)),
                ('IDc1', models.IntegerField(null=True)),
                ('IDc2', models.IntegerField(null=True)),
                ('project', models.OneToOneField(to='api.Project')),
            ],
        ),
    ]
